### ISSUE TITLE
[RuntimeError: CUDA out of memory] when max dimensions of final image are increased

### ISSUE THREAD

**Issue by VygintasC** [braindotai/Watermark-Removal-Pytorch#14]
I am getting the following error when I increase the --max-dim parameter above 700 on a 6GiB GPU. 

`RuntimeError: CUDA out of memory. Tried to allocate 208.00 MiB (GPU 0; 6.00 GiB total capacity; 5.29 GiB already allocated; 0 bytes free; 5.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I tried reducing the --input-depth to see if this would reduce the memory usage, but it didn't help. 

Are there any other possible tweaks that would allow for processing of larger images?

**Comment by Jamesong7822** [comment]
Hi @VygintasC , I would think the solution would be to add your own `preprocessing` script which slices the input image & mask to the dimensions that can be handled by your computer memory. It should not be too difficult to afterwards write some code to stitch the sliced images up again (`opencv`).

**Comment by braindotai** [comment]
The error explains that the GPU doesn't have enough memory to perform the necessary computation, probably because you're setting --max-dim too high. Every GPU has limitations, can't do much about it for the most part unless you upgrade your hardware, so you can start reducing the --max-dim size for the best-case scenario since you want high-resolution outputs until it works.

One slightly tricky and lengthy solution might be to divide your high-resolution watermarked image and its mask into small patches as @Jamesong7822 mentioned... you can do it manually or implement your splitting function, and run the pipeline on each patch pair.
