### ISSUE TITLE
Need some data on performance of this application

### ISSUE THREAD

**Issue by krishnatgkk123** [braindotai/Watermark-Removal-Pytorch#4]
First of all, Thank you very much for this program. It is working great for an image.

Currently, I am running this application on a windows laptop and was able to execute the program python inference.py.
I do have training-steps as 3000 which is the default.  i have prepared a masked image to remove the watermark from the original image. it is taking nearly 6hrs for an image to be processed and remove the watermark.

I wanted to know if I am doing anything wrong or will it be better if I run on some computer with good CPU power.

**Comment by braindotai** [comment]
Glad to know thay ur enjoying the implementation.

**THOUGH I HAVE TO SAY, USING IT FOR A REASON OTHER THAN EDUCATIONAL PURPOSES IS NOT APPRECIATED/ENCOURAGED.**

Now back to your issue, I'd suggest you to opt for GPU if possible, otherwise you can use Google colab which provides free GPU runtimes. And on google colab it would take just minutes on a single run.
